### ISSUE TITLE
Postgresql 9.5

### ISSUE THREAD

**Issue by jstans** [dalibo/pg_log_authfail#2]
I'm trying to set this up with a new postgres install and although it seems to build with the postgres 9.5 header files and place in the correct directory, I'm getting the following error back from the log files:

2016-01-12 17:22:33 GMT [29967-1] FATAL:  incompatible library "/usr/lib/postgresql/9.5/lib/pg_log_authfail.so": version mismatch
2016-01-12 17:22:33 GMT [29967-2] DETAIL:  Server is version 9.5, library is version 9.4.

Any ideas?

**Comment by rjuju** [comment]
I can only think of previous build or env issue.

Have you tried to do a "make clean" before compiling?
Otherwise, maybe different env variables if you do "make" then "sudo make install"?

If it's none of these, what is the ouput of "pg_config" (or sudo pg_config depending on how you're proceeding).

**Comment by jstans** [comment]
make clean solved it. I think it was because I installed the 9.4 headers first by accident and then didn't make clean after I realised my mistake; I just assumed it built correctly as it used the right directory. Thanks!

**Comment by rjuju** [comment]
Good news.

Thanks.
