### ISSUE TITLE
Help with Installation

### ISSUE THREAD

**Issue by mdstreet** [dalibo/pg_log_authfail#5]
Dear Sir,

Sorry for my ignorance but I am unable to find the tarball for your product. I can see the pg_log_authfail.c but I must be missing files as when I try to make install nothing happens. I am new to compiling files from GitHub. Any help would be greatly appreciated. I am using Centos 7 and PostgreSQL 9.4 and I have install the Centos 7 development tools. 
Thanks for your help

Mark Street

**Comment by rjuju** [comment]
Hello,

You can find tarball here: https://github.com/dalibo/pg_log_authfail/releases

To be able to compile this lib, you also need the postgres devel package (postgresql94-devel if you're using pgdg repository), and you should have your environment configured so that `pg_config` binary is in your path and points to your 9.4 binary (as root if you're using packages).
